# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_all": "00_core.ipynb",
         "children": "00_core.ipynb",
         "recursively_apply_to_children": "00_core.ipynb",
         "bn_to_tanh": "00_core.ipynb",
         "AdjustNormFunc": "00_core.ipynb",
         "tanSigmoid": "00_core.ipynb",
         "gaussian": "00_core.ipynb",
         "TanHNorm": "00_core.ipynb",
         "TanSigmoidNorm": "00_core.ipynb",
         "GaussianNorm": "00_core.ipynb",
         "recursive_getattr": "00_core.ipynb",
         "recursive_setattr": "00_core.ipynb",
         "modify_network": "00_core.ipynb"}

modules = ["core.py",
           "resnet34_experiment.py",
           "simple_cnn_experiment.py"]

git_url = "https://github.com/akashpalrecha/tanhNorm/tree/master/"

def custom_doc_links(name): return None